//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.EModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAdminRole
    {
        public void AdminRole()
        {
            this.AdminRoleAuth = new HashSet<AdminRoleAuth>();
        }
    
        public int AdminRoleID { get; set; }
        public int DepartmentID { get; set; }
        public string AdminRoleName { get; set; }
    
        public virtual ICollection<AdminRoleAuth> AdminRoleAuth { get; set; }
    }
}
