//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.EModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EAdminPage
    {
        public void AdminPage()
        {
            this.AdminPageAuth = new HashSet<AdminPageAuth>();
            this.AdminRoleAuth = new HashSet<AdminRoleAuth>();
            this.AdminUserAuth = new HashSet<AdminUserAuth>();
        }
    
        public int AdminPageID { get; set; }
        public string AdminPageTitle { get; set; }
        public string AdminPageURL { get; set; }
        public int AdminPageParentID { get; set; }
        public string AdminPageRemark { get; set; }
        public int AdminPageRank { get; set; }
        public int AdminPageIsVisible { get; set; }
        public int AdminPageIsLock { get; set; }
        public string AdminPageImgSrc { get; set; }
        public string AdminPageColor { get; set; }
    
        public virtual ICollection<AdminPageAuth> AdminPageAuth { get; set; }
        public virtual ICollection<AdminRoleAuth> AdminRoleAuth { get; set; }
        public virtual ICollection<AdminUserAuth> AdminUserAuth { get; set; }
    }
}
