//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.EModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESEMTemp
    {
        public int SEMTempID { get; set; }
        public string SEMTempTitle { get; set; }
        public string SMSTemplate { get; set; }
        public string EmailTemplate { get; set; }
        public int SEMIsSystem { get; set; }
        public string MessageTemplate { get; set; }
        public string SEMCode { get; set; }
    }
}
