//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAdminAction : SEBaseModel
    {
        public int? AdminActionID { get; set; }
        public string AdminActionName { get; set; }
        public string AdminActionTag { get; set; }
        public string AdminActionImgSrc { get; set; }
        public string AdminActionColor { get; set; }
        public string AdminActionRemark { get; set; }
        public int? AdminActionRank { get; set; }
    }
}
