//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAgentType : SEBaseModel
    {
        public int? AgentTypeID { get; set; }
        public string AgentTypeName { get; set; }
        public System.DateTime? AgentTypeCreateDate { get; set; }public System.DateTime? FromAgentTypeCreateDate { get; set; }public System.DateTime? ToAgentTypeCreateDate { get; set; }
        public string AgentTypeCode { get; set; }
    }
}
