//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAgent : SEBaseModel
    {
        public int? AgentID { get; set; }
        public string AgentNo { get; set; }
        public string AgentBigArea { get; set; }
        public int? AgentProvID { get; set; }
        public int? AgentCityID { get; set; }
        public string AgentName { get; set; }
        public string AgentNameA { get; set; }
        public string AgentNameF { get; set; }
        public string AgentTypeCode { get; set; }
        public int? AgentIsUserJiamiGou { get; set; }
        public string AgentJiaMiGouID { get; set; }
        public Nullable<int> AgentParentID { get; set; }
        public Nullable<int> AgentIsUsedSMS { get; set; }
        public Nullable<int> AgentIsSet { get; set; }
        public Nullable<int> AgentIntType { get; set; }
        public string AgentTeamBoss { get; set; }
        public int? AgentIsDel { get; set; }
        public int? AgentStatus { get; set; }
    
        public virtual AgentDetail AgentDetail { get; set; }
    }
}
