//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAttachFile : SEBaseModel
    {
        public int? AFID { get; set; }
        public string AFObject { get; set; }
        public int? AFSort { get; set; }
        public string AFNewName { get; set; }
        public string AFName { get; set; }
        public int? AFRank { get; set; }
        public int? AFIsMain { get; set; }
        public int? AFIsShow { get; set; }
    }
}
