//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEBulletin : SEBaseModel
    {
        public int? BulletinID { get; set; }
        public int? BullAddUserDepartID { get; set; }
        public int? BullAddUserRoleID { get; set; }
        public int? BullAddUserID { get; set; }
        public System.DateTime? BullAddTime { get; set; }public System.DateTime? FromBullAddTime { get; set; }public System.DateTime? ToBullAddTime { get; set; }
        public string BullTitle { get; set; }
        public string BullDes { get; set; }
    }
}
