//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECompany : SEBaseModel
    {
        public int? ComID { get; set; }
        public string ComName { get; set; }
        public string ComNameA { get; set; }
        public string ComNameF { get; set; }
        public string ComSName { get; set; }
        public string ComLogo { get; set; }
        public string ComLegalPerson { get; set; }
        public string ComContactPerson { get; set; }
        public string ComPhone { get; set; }
        public string ComTelPhone { get; set; }
        public string ComEmail { get; set; }
        public string ComAddress { get; set; }
        public string ComBarcodeType { get; set; }
        public int? ComStatus { get; set; }
        public string ComRemark { get; set; }
        public string ComSubRemark { get; set; }
        public string ComAddUserName { get; set; }
        public System.DateTime? ComAddTime { get; set; }public System.DateTime? FromComAddTime { get; set; }public System.DateTime? ToComAddTime { get; set; }
    }
}
