//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGouConfig : SEBaseModel
    {
        public int? GCID { get; set; }
        public int? GAgentID { get; set; }
        public int? GAdminUserID { get; set; }
        public int? GAdminUserNo { get; set; }
        public string GID { get; set; }
        public int? GStatus { get; set; }
        public System.DateTime? GAddTime { get; set; }public System.DateTime? FromGAddTime { get; set; }public System.DateTime? ToGAddTime { get; set; }
        public string GAddUserName { get; set; }
        public string GRemark { get; set; }
    }
}
