//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model.SEModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESendEmailQueue : SEBaseModel
    {
        public int? ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientEmail { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> QueueType { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }public Nullable<System.DateTime> FromSendDate { get; set; }public Nullable<System.DateTime> ToSendDate { get; set; }
    }
}
