//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserAuth
    {
        public int AdminUserAuthID { get; set; }
        public int AdminUserID { get; set; }
        public int AdminPageID { get; set; }
        public int AdminUserAuthRelID { get; set; }
        public int AdminUserAuthRelType { get; set; }
        public int AdminUserDicType { get; set; }
        public Nullable<int> AdminUserAuthRank { get; set; }
        public Nullable<int> AdminUserAutFiexd { get; set; }
    
        public virtual AdminPage AdminPage { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
