//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUser()
        {
            this.AdminUserAuth = new HashSet<AdminUserAuth>();
        }
    
        public int AdminUserID { get; set; }
        public string AdminUserName { get; set; }
        public string AdminUserNameA { get; set; }
        public string AdminUserNameF { get; set; }
        public string AdminUserNo { get; set; }
        public string AdminUserPass { get; set; }
        public int AgentID { get; set; }
        public int DepartmentID { get; set; }
        public int AdminRoleID { get; set; }
        public int AdminUserStatus { get; set; }
        public int AdminUserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUserAuth> AdminUserAuth { get; set; }
        public virtual AdminUserDetail AdminUserDetail { get; set; }
    }
}
