//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRoleAuth
    {
        public int AdminRoleAuthID { get; set; }
        public int AdminRoleID { get; set; }
        public int AdminPageID { get; set; }
        public int AdminRoleRelID { get; set; }
        public int AdminRoleRelType { get; set; }
        public Nullable<int> AdminRoleDicType { get; set; }
    
        public virtual AdminPage AdminPage { get; set; }
        public virtual AdminRole AdminRole { get; set; }
    }
}
