//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentCustType
    {
        public int AgentCustTypeID { get; set; }
        public string AgentCusTypeName { get; set; }
        public System.DateTime AgentCusCreateDate { get; set; }
        public int AdminUserID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AdminRoleID { get; set; }
        public string AgentCompanyName { get; set; }
        public Nullable<int> AgentCustUserType { get; set; }
        public string AgentReamrk { get; set; }
    }
}
