//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDictionary
    {
        public int DataDictionaryID { get; set; }
        public int DictionaryGroupID { get; set; }
        public string DataTableName { get; set; }
        public string DictionaryCode { get; set; }
        public string DictionaryName { get; set; }
        public string DictinaryCodeDIY { get; set; }
        public int DictionaryRank { get; set; }
    }
}
