//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
        public string DepartmentNo { get; set; }
        public int ParDepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentUsername { get; set; }
        public string DepartmentTel { get; set; }
        public string DepartmentFax { get; set; }
        public int DepartmentStatus { get; set; }
        public string DepartmentRemark { get; set; }
        public string DepartmentArray { get; set; }
    }
}
