//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetTemplateEntities : DbContext
    {
        public NetTemplateEntities()
            : base("name=NetTemplateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAction> AdminAction { get; set; }
        public virtual DbSet<AdminLoginLog> AdminLoginLog { get; set; }
        public virtual DbSet<AdminPage> AdminPage { get; set; }
        public virtual DbSet<AdminPageAuth> AdminPageAuth { get; set; }
        public virtual DbSet<AdminRole> AdminRole { get; set; }
        public virtual DbSet<AdminRoleAuth> AdminRoleAuth { get; set; }
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<AdminUserAuth> AdminUserAuth { get; set; }
        public virtual DbSet<AdminUserDetail> AdminUserDetail { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AgentCustDetail> AgentCustDetail { get; set; }
        public virtual DbSet<AgentCustType> AgentCustType { get; set; }
        public virtual DbSet<AgentDetail> AgentDetail { get; set; }
        public virtual DbSet<AgentType> AgentType { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<AttachFile> AttachFile { get; set; }
        public virtual DbSet<Bulletin> Bulletin { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DictionaryGroup> DictionaryGroup { get; set; }
        public virtual DbSet<EmailHistory> EmailHistory { get; set; }
        public virtual DbSet<GouConfig> GouConfig { get; set; }
        public virtual DbSet<GroupClient> GroupClient { get; set; }
        public virtual DbSet<Log4> Log4 { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<SEMTemp> SEMTemp { get; set; }
        public virtual DbSet<SendEmailQueue> SendEmailQueue { get; set; }
        public virtual DbSet<SMSHistory> SMSHistory { get; set; }
        public virtual DbSet<WeiXinHis> WeiXinHis { get; set; }
        public virtual DbSet<WeiXinRec> WeiXinRec { get; set; }
    }
}
