//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XG.Temp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSHistory
    {
        public int SMSHistoryID { get; set; }
        public string SMSTitle { get; set; }
        public int SMSUserID { get; set; }
        public string SMSTelNo { get; set; }
        public int SEMTemplateID { get; set; }
        public string SMSContent { get; set; }
        public int SMSSendStatus { get; set; }
        public System.DateTime SMSSendTime { get; set; }
        public Nullable<int> SMSTypeID { get; set; }
    }
}
